### ISSUE TITLE
`detail` in `Hypothesis`

### ISSUE THREAD

**Issue by gufranpathan** [ErikOSorensen/rgtools#14]
Are the `detail` and `detail_exp` no longer accepted by the schema? If so, do we need to modify the README description to reflect that?

**Comment by ErikOSorensen** [comment]
I have added implementations and modified the documentation slightly such that `xml <detail>` is either `true` or `false` which are the default xml-notation for booleans. In commit 927dbff.

**Comment by gufranpathan** [comment]
@VivianeHelena, FYI.
