### ISSUE TITLE
`armgroups` not accepting a second `armgroup`

### ISSUE THREAD

**Issue by gufranpathan** [ErikOSorensen/rgtools#15]
`armgroups` throw an error when a second `armgroup` is added. Consider the following xml:

```xml
  <armgroups>
    <armgroup>
      <label>letter</label>
      <armlabel>letter</armlabel>
    </armgroup>
    
    <armgroup>
      <label>control</label>
      <armlabel>control</armlabel>
    </armgroup>
  </armgroups>
```

The second `armgroup` throws the following error:

> cvc-complex-type.2.4.d: Invalid content was found starting with element 'armgroup'. No child element is expected at this point.xml(cvc-complex-type.2.4.d)

A few incidental questions:
1. Are `armgroups` mandatory?
2. In the hypothesis, is an `arm` interchangable with an `armgroup`, i.e. can I enter the label of an `armgroup` in an `arm`? Or should we distinguish between the two so we know which element is being referenced to avoid collision of same label of an `arm` and an `armgroup`?
3. Perhaps we need to add documentation for `armgroups` in the README. Need a new issue?

**Comment by ErikOSorensen** [comment]
I have attempted to clarify in both the schema and the README documentation.

1. `xml <armgroups>` is optional. In case it is included, there is only one such element which contains each specific armgroup.
2. For now, there is a non-enforced requirement that an armgroup gets a label that is different from the labels used for arms. 
3. I have added a some text and an example. 

Could you take a look and determine if this closes the issue?

**Comment by gufranpathan** [comment]
@VivianeHelena, FYI.
