### ISSUE TITLE
'det_exp' use

### ISSUE THREAD

**Issue by VivianeHelena** [ErikOSorensen/rgtools#17]
Hi Erik,

Given what is mentioned in the README file, namely
> det_exp
String variable, conditional on the hypothesis not being detailed enough (detail = "false"). [...]

Gufran and I have noticed that `<det_exp>` comes up as mandatory during encoding even when `<detailed>` = "true".
Could you please verify on your end?

Thanks!

NB: the code accepts the element name being `<detailed>` rather than `<detail>`. There are a couple of mentions in the README file without the "-ed" at the end.

**Comment by ErikOSorensen** [comment]
I have attempted to clarify and fix documentation in commit e4db09e. 

- The element should be called `<detailed>`
- I have made the `<det_exp>` element optional. Ideally it should  be mandatory if `<detailed>false</detailed>` and not possible when `<detailed>true</detailed>` but this level of sophistication needs a bit more thought.

**Comment by VivianeHelena** [comment]
@gufranpathan fyi
