### ISSUE TITLE
Add `version` element in schema

### ISSUE THREAD

**Issue by gufranpathan** [ErikOSorensen/rgtools#19]
It would be useful to record the `version` of the trial registration in cases where we code the study using an older version. This may be needed when the registration has been updated after data collection and a previous version of the registration may be considered more 'blind' to the outcomes.

**Comment by gufranpathan** [comment]
@ErikOSorensen, I was wondering if I could ask your help with this, please? I'm also happy to take this up if you're pressed for time - might take me a bit longer to understand the `.xsd`.

**Comment by ErikOSorensen** [comment]
Added a new (mandatory) field in 2461df6 : `registration_version`. An empty field is written by the templating program.
