### ISSUE TITLE
`data_publication` field 

### ISSUE THREAD

**Issue by VivianeHelena** [ErikOSorensen/rgtools#20]
While working on 608, I noticed that the `data_publication` field generated automatically for this study in G0 says `Yes`, although the [registration](https://www.socialscienceregistry.org/trials/608) says `No`. Could you verify the field/what might have happened, please?

**Comment by VivianeHelena** [comment]
@gufranpathan fyi

**Comment by ErikOSorensen** [comment]
Fixed in commit 7aeda00.
