### ISSUE TITLE
Docs for `seperate_effects` and `different_effects`

### ISSUE THREAD

**Issue by gufranpathan** [ErikOSorensen/rgtools#21]
Need to add documentation on what we mean by `seperate_effects` and `different_effects` when coding `test_heterogeneity`.

**Comment by ErikOSorensen** [comment]
A `separate_effects` being true indicates that there are hypothesis about the effect in each of the indicated subgroups.

A `different_effects` being true indicates that there is a hypothesis about the effect being the same in the indicated subgroups.

Added to README in version 4f10412
